### ISSUE TITLE
Unify all data removal policies

### ISSUE THREAD

**Issue by erkinalp** [github/site-policy#112]
Unify DMCA takedown policy and Sensitive Data Removal policy into single Data Removal Policy.

**Comment by LostInc1986** [comment]
Uneducated at the issue at hand.
-Yousef Muhammad Saeed

**Comment by LostInc1986** [comment]
Peace and Serenity!

**Comment by LostInc1986** [comment]
Sincerly,
-Yousef Muhammad Saeed

**Comment by bluemazzoo** [comment]
Minimizing those comments as off topic.

**Comment by Golfry66** [comment]
It ok

**Comment by vollmera** [comment]
Apologies for the delay in responding. 

We do now have a [Submitting content removal requests](https://help.github.com/en/github/site-policy/submitting-content-removal-requests) page that links to both of these policies.

We keep those policies in full separate so that it's clear for reporting users what to provide.
