### ISSUE TITLE
Some dead links I found in the ToS that are probably also in other places

### ISSUE THREAD

**Issue by Volleo6144** [github/site-policy#119]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?
N/A

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
Well, I found this in [the DMCA section of the Terms of Service](https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#f-copyright-infringement-and-dmca-policy), but I think it may be in other places as well.

#### 3. Did you already open a pull request? If so, please include a link to the PR.
Nope.

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
Most of the links in [here](https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#f-copyright-infringement-and-dmca-policy) are dead, so maybe we should fix them. (They link to master/articles/NAME#SECTION instead of master/Policies/NAME.md#SECTION.)

#### 5. Why do you think this section or language needs improvement?
Dead links are never okay on something that isn't abandoned (and you haven't abandoned your Terms of Service), so...yeah.

**Comment by nsqe** [comment]
Thanks, @Volleo6144. 

We generally mention, in the pull request itself, that links in this repository aren't ever going to work. This repository doesn't house the files that are referenced on the website (in other words, https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md isn't what's serving https://help.github.com/articles/github-terms-of-service/ — we have to do some other work on the back end, and the actual files are stored in a different location). 

Because the files that are actually served from our pages are in a different location, their relative links are going to be different. But when we've got a policy in this repo, we want to faithfully show you the exact same file that we're using, unedited, so you know we're not doing any surreptitious policy changes without the transparency our users expect.

So...the links here won't work. 

But please let us know if you see any dead links in the working files, and we'll take care of it!

**Comment by j-f1** [comment]
How about using absolute links instead (i.e. `https://help.github.com/foo` instead of `/foo`)?

**Comment by nsqe** [comment]
You know...you're probably right. Absolute links are generally safer than relative links. Thanks, @j-f1, I'll open an issue internally.
