### ISSUE TITLE
Is being a Nazi permitted by GitHub site policy?

### ISSUE THREAD

**Issue by joshua-s** [github/site-policy#357]
A few days ago, a Jewish GitHub employee was rebuked and fired for warning colleagues to "stay safe ... Nazis are about." This was after the storming of the Capitol by terrorists wearing "6MWE" and "Camp Auschwitz" shirts.

Since nazis are apparently respected and protected at GitHub, I was wondering when you'd be updating your site policy to make this clear? /S

**Comment by KOLANICH** [comment]
IMHO: GitHub should not join this political circus campaign against Trump supporters. 

P. S. Godwin's law works, as usual.

**Comment by joshua-s** [comment]
@KOLANICH that crowd included known neo-nazis and others wearing Nazi apparel. It is not off-base to call a nazi a "nazi".

**Comment by KOLANICH** [comment]
I don't care if they are "nazi"s or not. They have civil rights, we all have civil rights. One of such rights is a freedom of speech. It doesn't matter who is gonna be deprived of a civil right, as long as someone is deprived, everyone is deprived, because the sole fact of depriving anyone of a civil right means that people can be deprived of it. Yesterday it was "nazis", tommorrow it can be anyone else, maybe even you. Instead of arguing about whom to deprive of the right you should argue that it is completely inacceptable to deprive anyone of the right.

And yes, what is going on is censorship, even if FAGM are enterprises, and even if they have right to do this on own platforms (maybe at expense of their popularity and stock prices, with sites like Palmer taking advantage of being more freedom-of-speech-friendly, despite being used by far-right folks), it doesn't change one simple thing that when a big and powerful entity does this, it is a censorship. They can do it, they have right to do that, but their reputation will never be restored after it.

**Comment by mlinksva** [comment]
Antisemitism, neonazis, and white supremacy – along with all other forms of racism – have no place in our community. Please refer to our [acceptable use policy](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-acceptable-use-policies) and [community guidelines](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines) for guidance.
