### ISSUE TITLE
The term "fork" is not defined anywhere in the GitHub Terms of Service

### ISSUE THREAD

**Issue by evandrocoan** [github/site-policy#37]
There are several interpretations for what does the term `Fork` means, and the Terms of Service does not define of the them. Which is basically ask for trouble for the GitHub users which use the fork button on non-open source projects. As many of them comply to the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention) on the absence of a explicit license.

Moreover following on the Open Source Stack Exchange questions:

1. [What does the 'right to fork' mean?](https://opensource.stackexchange.com/questions/345/what-does-the-right-to-fork-mean)
1. [How does GitHub's “forking right” cope with an “All rights reserved” project?](https://opensource.stackexchange.com/questions/1154/how-does-githubs-forking-right-cope-with-an-all-rights-reserved-project)

There are at least two understandings about what does a fork mean. They are respectively:

1. > [quoting: [Gilles](https://opensource.stackexchange.com/users/60)] The right to fork refers to [forking](https://en.wikipedia.org/wiki/Fork_(software_development)) as in taking a software project and maintaining it separately from the original. Having the right to fork a work means having the right to modify your own copy. In the context of freely distributable works, the right to fork means having the right to redistribute modified copies.
1. > [quoting: [apsillers](https://opensource.stackexchange.com/users/50)] **The term "fork" is not defined anywhere in the GitHub Terms of Service**, but it seems perfectly sensible to assume that "fork" here is meant in the sense that it is used elsewhere on github.com: the Fork button. <br/>
![a "Fork" button on a GitHub repository page](http://i.stack.imgur.com/lr4ml.png)<br/>
GitHub *probably* intends "the right to fork" to mean "the right to use the Fork feature of the github.com website." In this case, "creating a fork" would *not* mean generally creating a copy or derivative work (as it does in general FLOSS parlance), but rather it means *triggering the software of github.com to create and host a verbatim copy of a repository* and categorize that copy under the user's list of forks.<br/>
<details>
<p>

1. > [quoting: [Gilles](https://opensource.stackexchange.com/users/60)] The practical importance of the right to fork is that is you don't like the way the original author maintains the work (not fixing the bugs that bother you, not adding the features you wany, etc.) then you can do what you like with your own copy. Having the source (i.e. the prefered form of modification) is critical there, since it is the only practical way to fork a work. A right to fork without having the practical means to make use of it, i.e. having the source, would not be very useful. <br/>
The combination of being allowed to and able to modify the source and the right to redistribute allows anyone who's interested to take up maintenance. This is a guarantee that free software and other open source works won't die as long as someone somewhere, anywhere, is willing and able to take up maintenance. It's also a guarantee that if someone dislikes the way the project is maintained, they can make their own version if they're willing and able to invest the requisite effort or get someone to do it.
1. > [quoting: [apsillers](https://opensource.stackexchange.com/users/50)] If the original copyright owner doesn't license any other permissions, clicking that button is all that the TOS-required permission allows the user to do. This doesn't grant any rights to create a derivative work, or to redistribute the code outside of github.com, since the "Fork" feature is intrinsic to the github.com website. <br/>
Speculation: this right-to-fork language in the GitHub TOS was probably included to prevent legal issues around the use of the Fork feature. The intent was likely something to the effect of, "You must license the minimum amount of rights to allow github.com's Fork software feature to operate." <br/>
Based on this reading of "fork," if another user were to use a github.com-hosted forked-repository to prepare and distribute a derivative work, that would infringe on the owner's copyright, since such an action is outside the scope of the Fork software feature. Similarly, if the user were to create a verbatim copy outside the context of github.com's Fork functionality (e.g. copying the code to another website), that would also not be permitted. The TOS does not allow the right to create copies generally; it *only* requires the author to grant copying permission inasmuch as copying is a necessary component of the Fork feature.
</p>
</details><br/>

Currently the situation is open to a tribunal court do determine what rights the GitHub `Fork` button actually gives. As currently it is, it only implies the right to use the `Fork` button feature present on the site. Hence, a public GitHub repository complying with [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention) only, is very dangerous for GitHub users which `fork` it, and push commits/pull requests to their `fork`. As they are in great danger/liability of the prosecuted by the original repository owner, if they perform commits and pull requests due [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention) applied.

It follow because the repository is not giving any rights to anyone else, other then create a copy using the GitHub `Fork` button. Such feature is seems very useless, as if I want to `fork` a GitHub repository, is to apply bug fixes and new features not presented on the original repository. Or because I do not like the way the original author maintains the work, i.e., not fixing the bugs that bother you, not adding the features you want to, etc. 

Therefore as we can mostly see, thousands of GitHub repositories out there are complaining with the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention). I would suggest to apply to the `Fork` button feature, the ability/right to allow the forked repositories to receive push commits from their forkers and perform pull requests to the original repository.

In any case, if someone is putting their code on a GitHub public repository, but has no intention to allow others to `fork` their project and push commits/pull requests, they should:
1. Not put their code on a GitHub public repository. They should consider not put it on the internet or putting it on a GitHub private repository.
1. Explicitly apply a license to their project forbidden it, which should also disable the GitHub `Fork` button, and clearly alert/inform the GitHub user that this repository very dangerous as its contents are not allowed to be forked and consequently changed by git commits.

___

![image](https://user-images.githubusercontent.com/5332158/28265101-752b79be-6ac4-11e7-9117-b9d2ca7bce41.png)
https://en.wikipedia.org/wiki/License_compatibility

Related issues and threads:

1. https://github.com/github/site-policy/issues/7 OSS licences vs. ToS: grants of rights
1. https://github.com/SublimeText/LaTeXTools/issues/1175 Can it be an open source project?
1. [Fork (software development)](https://en.wikipedia.org/wiki/Fork_(software_development))
1. [Is it possible to get rich prosecuting GitHub users from a non-lincesed fork?](https://opensource.stackexchange.com/questions/5713/is-it-possible-to-get-rich-prosecuting-github-users-from-a-non-lincesed-fork)

<details>
<p>

![linux_distribution_timeline](https://user-images.githubusercontent.com/5332158/28232516-7f896938-68c7-11e7-91dc-f3ae57d43718.png)
</p>
</details>

**Comment by KOLANICH** [comment]
I vote for the approach "if you put that to an open github repo, you allow everybody to copy, modify, use and redistribute the content for any purpose (no "no-competition" licenses). Only licenses allowing this are allowed for open repos. If no or an unallowed (proprietary) license was specified, the default one (i advise to make the default one like cc0 or unlicense) is applied.". The next step is to find all the existing repos without an allowed license (the tricky part: there are repos imported from svn and licenses may be specified not as COPYING/(UN)LICENSE, but in the code itself, or even in metadata by spdx identifier), hide them from public (and disallow write access untill they choose what to do to prevent using them as private repos) and ask their owners what to do with their data: apply a free software license, apply the default license or delete the repo.

**Comment by mirabilos** [comment]
KOLANICH dixit:

>I vote for the approach "if you put that to an open github repo, you
>allow everybody to copy, modify, use and redistribute the content for

That would, again, exclude any and all copyleft licences, and indeed
most copycentre/copyfree licences (“permissive”) as well, since all
of the (with very few exceptions like WTFPL) put conditions on such
uses.

*sigh* Why do people make this mistake over and over again?

Same in #38, although that’d be not a problem if it would only apply
to repositories that are not already under a licence on my list of
free licence lists (cf. #7).

bye,
//mirabilos
-- 
(gnutls can also be used, but if you are compiling lynx for your own use,
there is no reason to consider using that package)
	-- Thomas E. Dickey on the Lynx mailing list, about OpenSSL

**Comment by KOLANICH** [comment]
Could you name the free open-source licenses imposing restrictions on uses other than distribution of modified code? I know no such. Even GPL (one of the most restrictive foss licenses) allows to do with the code everything except distributing the code on differrent terms. You can create competing products, you can install software on tivoized device, you are even not required to accept the license in order to use the program! Of course it's just gpl. But permissive licenses are usually even more permissive and allow you to close the source of modified versions. So I really don't understand how this should exclude them.

**Comment by apsillers** [comment]
KOLANICH, since the GPL requires derivative works to be distributed under the GPL, how would you reconsile that GPL requirement with a Github-required license grant to allow derivatives?

That is, if a license allows derivatives under any terms whatsoever (e.g., you must pay $1000, or get author approval, or not disrespect a particular nation's laws), should we craft the GitHub license terms to allow this requirement on top? If not (or if so), how?

**Comment by KOLANICH** [comment]
>KOLANICH, since the GPL requires derivative works to be distributed under the GPL, how would you reconsile that GPL requirement with a Github-required license grant to allow derivatives?

It doesn't require derivative works to be distributed at all.

**Comment by apsillers** [comment]
> It doesn't require derivative works to be distributed at all

Sure, but the entire point of this discussion is how GitHub should (or should not) handle the distribution of forks. I'll happily amend that sentence to, "the GPL requires derivative works *that are distributed* to be distributed under the GPL..." without loss of applicability to this topic.

I'm not sure how to meaningfully enumerate the properties that you call "copyright trolling", but I can appreciate a broad kind of good-faith/bad-faith distinction that the ToS might be able to hew out with some work. I can see this requiring a lot of work to keep out the bad-faith licenses without stepping on the good ones, along with a large dose of philosophical disagreement about which licenses are which kind, but this could be a workable solution if Github put in the time to write it and weathered the controversy over whether it was correct.

However, let me put forward one more problem: GPL compatibility. Suppose there are two original repos, one under the GPL and another under a GPL-incompatible FLOSS license. Certainly neither of these licenses run afoul of your "trolling" concerns, but if a downstream recipient tries to publish a fork that is a combination of these works, they are in violation of the GPL. I suppose your solution here might be, "Yes, the ToS should circumscribe its right-to-modify grant to allow normal operation of the GPL in blocking this combination, but only because the GPL is a good non-trolling license." Is that roughly correct?

**Comment by KOLANICH** [comment]
>I speculate your solution here might be, "Yes, the ToS should grant the right to distribute modifications, but circumscribe this right to allow normal operation of the GPL (and other copyleft) in blocking this combination, but only because the GPL is a good non-trolling license. If a bad-faith license tried to block this combination, it should not be allowed on Github." Is that roughly correct?

Nope. I haven't considered FOSS licenses clashes, I only considered mitigations of the case of

>Is it possible to get rich prosecuting GitHub users from a non-lincesed fork?

and proposed the solution to make everyone publishing content in a GH open repo to grant everyone accessing this content unconditional permission to copy, modify, use and probably share-alike (I personally vote for unconditional and prefer public-domain like licenses, but I understand that rejecting gpl-licensed projects will make GH bankrupt) permission (but without any conditions like "you are prohibited to use original product's name" or "you are prohibited to use the original developer's name") to distribute that content. If the license grants its permissions - fine. If it doesn't - the code automatically relicensed to the license granting them. For the clashes and other issues - GitHub (virtual) servers belong to GitHub, that's why GitHub can do anything it wants with own servers, including deleting repos and users from it, so if FSF disliked the repo, he could contact the repo owner and/or github to negotiate the situation.

**Comment by bluemazzoo** [comment]
>Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and _"fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control)._

>If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

Hi @evandrocoan, thank you for contributing. 

Above I have included the new draft of [Section 5. License Grant to Other Users](https://github.com/github/site-policy/blob/github-tos-update-july-2017/Policies/github-terms-of-service.md#5-license-grant-to-other-users) from the Terms of Service (emphasis added).  The italicized section includes a definition of "fork," i.e. that others may make their own copies of Content from your repositories in repositories they control. The second paragraph of that section includes the license grant required from users for others to fork their content on GitHub.

Feel free to reopen this issue if that does not answer your question, or open a PR If you prefer. Thanks again!

**Comment by mirabilos** [comment]
I’m a bit puzzled about this issue since the new (Feb 2017) ToS actually _do_ define what’s granted by a fork, which __is__ a major step forward from the previous ToS, modulo #7 of course.

**Comment by evandrocoan** [comment]
You are welcome @bluemazzoo, but still do not understand when you say:

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).

The words `to use, display, and perform`, means I can `through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality`:

1. Create pull requests using the GitHub pull requests feature?`
    <details>
    <p>

    ![image](https://user-images.githubusercontent.com/5332158/28288083-6300732a-6b14-11e7-91fb-3cb3f60bf13e.png)
    </p>
    </details>
1. Use the GitHub edit feature and create commits?
    <details>
    <p>

    ![image](https://user-images.githubusercontent.com/5332158/28288034-303b4e42-6b14-11e7-8f94-e5ef7c9b5ca3.png)
    </p>
    </details>

**Comment by wking** [comment]
On Mon, Jul 17, 2017 at 10:54:45PM +0000, Evandro Coan wrote:
> The words `to use, display, and perform`, means I can `through the
> GitHub Service and to reproduce Your Content solely on GitHub as
> permitted through GitHub's functionality`:
> 
> 1. Create pull requests using the GitHub pull requests feature?`
>     <details>
>     <p>
> 
>     ![image](https://user-images.githubusercontent.com/5332158/28288083-6300732a-6b14-11e7-91fb-3cb3f60bf13e.png)
>     </p>
>     </details>
> 1. Use the GitHub edit feature and create commits?
>     <details>
>     <p>
> 
>     ![image](https://user-images.githubusercontent.com/5332158/28288034-303b4e42-6b14-11e7-8f94-e5ef7c9b5ca3.png)
>     </p>
>     </details>

These seems separate from “fork”, since that now explicitly covers
only making copies.  I agree that whether “use” covers sharing new
commits is not clear to me.

**Comment by evandrocoan** [comment]
@bluemazzoo, I opened a pull request on the branch you have been working ([github-tos-update-july-2017](https://github.com/github/site-policy/tree/github-tos-update-july-2017)) trying to elaborate on the fork definition, accordingly to the article:

1. https://help.github.com/articles/dmca-takedown-policy/#b-what-about-forks-or-whats-a-fork
