### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by dr-dimitru** [github/site-policy#40]
#### 1. What's the name of the policy?
[amendment-to-github-terms-of-service-applicable-to-u-s-federal-government-users.md](https://github.com/github/site-policy/blob/master/Policies/amendment-to-github-terms-of-service-applicable-to-u-s-federal-government-users.md)

#### 2. Reason:
All links in [this](https://github.com/github/site-policy/blob/master/Policies/amendment-to-github-terms-of-service-applicable-to-u-s-federal-government-users.md) document are broken

**Comment by bluemazzoo** [comment]
@dr-dimitru Thank you for contributing. 

Unfortunately, since all of the site policies are direct copies from our [GitHubHelp page](https://help.github.com/categories/site-policy/), they contain the same local links as the live policies. 

If you'd like to take a look at our Amendment to GitHub Terms of Service Applicable to US Federal Government Users or any of the links on that policy, you can find the live policy [here](https://help.github.com/articles/amendment-to-github-terms-of-service-applicable-to-u-s-federal-government-users/).

**Comment by dr-dimitru** [comment]
Sure, but I don't see the reason not to use absolute links, will it be possible?
