### ISSUE TITLE
Minors should be able to use with parental consent

### ISSUE THREAD

**Issue by erkinalp** [github/site-policy#42]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?
GitHub Terms of Service - indirectly affects all policies by broadening who can use
#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#b-account-terms
Paragraph beginning in "You must be age 13 or older."
#### 3. Did you already open a pull request? If so, please include a link to the PR.
#43
#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
See above.
#### 5. Why do you think this section or language needs improvement?
Children under 13 have coding ability, too. They currently cannot use GitHub at all. If accepted, children under 13 will be able to join with a parent's consent (software changes are needed to implement this policy in order to prevent registering fake parent accounts)

**Comment by Tetizera** [comment]
Yeah, it seems like a no-brainer. The "13 years old thing" is usually just standard in legal documents of tech companies, though.

Does Khan Academy have something similar in their document? I guess they could be an example to check about it.

**Comment by erkinalp** [comment]
We all know the reason:children cannot consent to a binding contract by themselves. One-time irrevocable parental consent with retroactive deletion in violations is a reasonable compromise.

**Comment by erkinalp** [comment]
Added more clarification over parent's and child's IP stating child has a right to use parent's code ensured by parent.

**Comment by Natureshadow** [comment]
>We all know the reason: children cannot consent to a binding contract by themselves.

Of course they can. Under most jurisdictions, if their consent does not have legal downsides.

The reason is that GitHub copied COPPA without thinking and have useless insulting rules in their ToU that require consent to legal downsides.

**Comment by lee-dohm** [comment]
@Natureshadow your comment was deleted as a violation of the [Site Policy Code of Conduct](https://github.com/github/site-policy/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by Natureshadow** [comment]
>@Natureshadow your comment was deleted as a violation of the [Site
>Policy Code of
>Conduct](https://github.com/github/site-policy/blob/master/CODE_OF_CONDUCT.md)
>as it was insulting or derogatory. You may consider this an official
>warning.

Hah, what :D?

Now this makes GitHub finally unusable. There was NOTHING like that in my comment. Please prove that my comment violated this policy - deleting it and then making questionnable statements about it looks really weird.

**Comment by mirabilos** [comment]
Why would the parent need to have any age restriction except being 13 years or older?

(I can think of some very extreme cases where an under-18 parent could have a legal child old enough to code, and I see nothing that restricts this.)

I was told the age limit of 13 was due to COPPA and “nothing could be done about it”. As European, I can only shake my head on this, but whatever. Consult a lawyer specific to the USA and gather what exactly is required, instead of creating potentially not legal stuff like this.

**Comment by nsqe** [comment]
As I mentioned in https://github.com/github/site-policy/pull/43, we are unable to allow minors under the age of 13 to have GitHub accounts. There are significant legal requirements (such as COPPA) regarding verifying parental consent, and we do not currently meet those requirements.

We completely agree, there are some really brilliant young coders out there, and we would love to encourage and nurture their skill. However, we don't have the ability to welcome them at this time.

**Comment by Natureshadow** [comment]
>We completely agree, there are some really brilliant young coders out
>there, and we would love to encourage and nurture their skill. However,
>we don't have the ability to welcome them at this time.

Which makes GitHub a discriminating p.o.s.

Block me if you want, but it will only give everyone less contributions and harm your image.

**Comment by Natureshadow** [comment]
To everyone watching: Feel free to move to https://edugit.org, going public within the next two weeks.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ssokolow** [comment]
@Natureshadow 

I'm sorry but, if that kind of name-calling and sour grapes behaviour is what you consider acceptable, I wouldn't want to send kids your way and risk that the community on edugit would teach them that such behaviour is acceptable in other parts of the open-source world.

**Comment by lee-dohm** [comment]
I deleted the above comment because it contained an advertisement.

**Comment by erkinalp** [comment]
Reconsider with MS acquistion. Microsoft has a very large team dedicated to child-friendly products.

**Comment by KOLANICH** [comment]
>Reconsider with MS acquistion. Microsoft has a very large team dedicated to child-friendly products.

I guess it is unneeded. Children can always claim that they are more than 13 years old and GH won't check it (for example by asking ID) even if it could. These are just protective legal words which are de-facto as enforceable as some games asking users to input their age on first launch or as a ToS of some well-known torrent tracker prohibiting its usage for everyone except its owners. If the age is raised to 16 years old it doesn't make any difference for everyone except well-known public persons whose age is known by everyone, and even this doesn't prevent them from using a nickname.

**Comment by ssokolow** [comment]
Not necessarily. I'm preparing to backup what I have on GitHub for fear that the acquisition by Microsoft will lock me out of GitHub the same way they locked me out of Hotmail for not owning a smartphone that could be paired with it.

**Comment by erkinalp** [comment]
16 years is GDPR&ePrivacy majority age. Microsoft has a team dedicated to child&family friendly software, hence they can adapt GitHub to be child friendly both in consent collection and other aspects.

**Comment by KOLANICH** [comment]
>Microsoft made sharing your smartphone number mandatory to log back into existing Hotmail accounts, which means that, if my old Hotmail account still exists, I can't get into it.

Ouch :( . Luckily, I don't have any private repos here. All I lose is interactions to the ones who are not #moving.

**Comment by mirabilos** [comment]
You seem to be awfully dependent on the location of the central repository of your decentral version control system…

**Comment by ssokolow** [comment]
It's more about stuff that is inherently tied to being logged into GitHub, like a complete list of secret (ie. unlisted) gists which may not all be embedded in my self-hosted blog, and ensuring that I've got alternative login options for any 3rd-party services which I currently log into via GitHub OAuth.

The rest shouldn't be too difficult for me to backup anonymously.

**Comment by j-f1** [comment]
> a complete list of secret (ie. unlisted) gists

If you’re logged in, you can get that by going to <code>https:\//gist.github.com/<kbd>your-user-name</kbd>/secret</code>, i.e. https://gist.github.com/ssokolow/secret for you.

**Comment by ssokolow** [comment]
You misunderstand. I'm already well-aware of everything I need to do and how to do it. I was just giving you a sample of the checklist I intend to find time to go through over the next little while.

(Also, this is off-topic so we should stop.)

**Comment by iargent** [comment]
> I guess it is unneeded. Children can always claim that they are more than 13 years old and GH won't (I hope) check it (for example by asking an ID or stalking on social networks) even if it could.

It creates problems for me with teaching younger kids. Older kids can sign up for an account with a personal email and then fork a repository for a lesson. I can't ask younger kids to break the ToS. Getting all parents on board may not be possible because they do not want to sign up for a service they don't really understand. I guess the only way around it is for me to host my own git server which eats into time I would rather spend on preparing lessons.

**Comment by mirabilos** [comment]
iargent dixit:

>It creates problems for me with teaching younger kids. Older kids can
>sign up for an account with a personal email and then fork a repository
>for a lesson. I can't ask younger kids to break the ToS. Getting all
>parents on board may not be possible because they do not want to sign
>up for a service they don't really understand. I guess the only way
>around it is for me to host my own git server which eats into time I
>would rather spend on preparing lessons.

For what it’s worth, Teckids e.V. offers youth-friendly git hosting for
educative/related projects for free on https://edugit.org/

Of course this still precludes minors from contributing to github-hosted
projects but it may just suffice for your teaching situation (and if not
contact the charity; we may be able to figure out a solution).

bye,
//mirabilos
-- 
Thorsten Glaser (Founding Member)
Teckids e.V. — Digital freedom with youth and education
https://www.teckids.org/

**Comment by hikayamasan353** [comment]
Closing the issue and believing that you can't do anything about it because of COPPA requirements being too harsh only shows that you are not willing to understand COPPA itself, as well as your cowardice.

You clearly admit that COPPA requires parental consent and that children actually can code and there are kids who code. That sets you apart from people around the internet who claim that zero tolerance blanket age restrictions, which you implement, are necessary because of COPPA (in reality, again, COPPA requires parental consent), as well as that kids under 13 don't belong on any online services or communities because of whatever comes to your mind (inappropriate content, inappropriate behaviour aka "creeps"/"pedophiles" etc).

But here's the thing - you don't want to even try doing anything to even implement placeholder or experimental features for testing parental consent. And I can guess why - you fear that FTC will sue you (COPPA lawsuits fines are huge) even if you have actually had implemented parental consent. This is exactly why you're a coward.

And I can tell why. You don't want to hire and train personnel to staff a toll free phone line or video chat, nobody uses a fax nowadays, international phone calls and mail correspondence are expensive, and some parental consent requirements can be intimidating to parents themselves.

But fortunately, we can implement COPPA parental consent with digital forms. Currently, it's easy to send a consent letter via email or a digital form. We can use government ID card pictures (it's very easy - few people have scanners but everyone has a smartphone or tablet, and it's very easy to just snap a picture of a government ID), as well as charge debit card fees to verify the identity of the parent. That might seem intimidating, but it's essential for verifiability in parental consent. That's not to mention that even just email can be used for parental consent - but there are certain limitations of what can be done if just an email is used as a parental consent.

This is also a big flaw of COPPA itself. FTC should realise that heavy fines (what about prison sentences???) will only make online services avoid obtaining parental consent, excluding kids under 13 instead. This is exactly what you do.

If FTC somehow helped online services to comply with their own law, and understood that keeping kids under 13 off the online services entirely is neither doable nor good - because enforcing a lawsuit costs money regardless of potential fines as "revenue", and kids will always be there, lying about their age or bypassing parental consent. You don't enforce laws simply to make defendants pay fines - that's extortion!!!

In addition, you should also consider how the age restrictions are affecting kids.

Will kids ever get over it and wait until 13? No, no and no. They will lie about their ages (and they already do), and parents will create accounts for them and manage them instead.

If we tell kids that they should wait until 13 because there's NSFW content and pedophiles lurking online to kidnap them, it will build fear in them, as well as give them an idea that it's the kids fault for being too young.

And if we admit to the kids that they can't register before 13 because you can't get their parental consent, it will send them a message that we're failing them.
