### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bnb** [github/site-policy#514]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?
GitHub Acceptable Use Policies

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
`2. Content Restrictions`

#### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).
No.

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
It seems that a link is broken. Specifically, the link on the text `unlawful active attack or malware campaigns` seems to point to a file in this repo that has been refactored away. It would be nice to either update the link (I'd PR if I found an obvious descendant of that page, but alas I didn't) or remove the link.

#### 5. Why do you think this section or language needs improvement?
Clarity about Acceptable Use is important :)

**Comment by bnb** [comment]
also, if it helps, I'd be happy to PR [JustinBeckwith/linkinator-action](https://github.com/JustinBeckwith/linkinator-action) in to this repo to automatically handle dead link checking :)

**Comment by margaret-tucker** [comment]
Thanks, @bnb. I'm closing this with an explanation:

We generally mention, in the pull request itself, that links in this repository aren't ever going to work. This repository doesn't house the files that are referenced on the website (in other words, https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md isn't what's serving https://help.github.com/articles/github-terms-of-service/ — we have to do some other work on the back end, and the actual files are stored in a different location).

Because the files that are actually served from our pages are in a different location, their relative links are going to be different. But when we've got a policy in this repo, we want to faithfully show you the exact same file that we're using, unedited, so you know we're not doing any surreptitious policy changes without the transparency our users expect.

So...the links here won't work.

But please let us know if you see any dead links in the working files, and we'll take care of it!
