### ISSUE TITLE
Is writing open-source code illegal? — Tornado Cash

### ISSUE THREAD

**Issue by ylemkimon** [github/site-policy#600]
#### 1. What's the name of the policy?

GitHub Terms of Service

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/blob/main/Policies/github-terms-of-service.md#3-account-requirements

> You may not use GitHub in violation of export control or sanctions laws of the United States or any other applicable jurisdiction.

#### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).

TBA

#### 5. Why do you think this section or language needs improvement?

Recently, GitHub [has taken down the Tornado Cash organization and suspended their developer's account](https://www.theregister.com/2022/08/10/github_tornado_cookies/).

Was it in response to the U.S. government's request? If so, please publicly post the notice on https://github.com/github/gov-takedowns.

Furthermore, writing an open-source code should not be considered a direct violation of sanctions law and thus not a violation of the GitHub ToS. It should be protected by the freedom of speech (or the First Amendment for those in the U.S.).

Please reconsider the decision to take down repositories and revise the ToS to ensure that the free speech rights of developers are protected.

See also https://www.eff.org/deeplinks/2022/08/code-speech-and-tornado-cash-mixer.

**Comment by KOLANICH** [comment]
>Is writing open-source code illegal

Not a lawyer and clearly not your or anyone's else attorney, but it is not illegal to write source code. It is "de-facto illegal" (strongly discriminated against by the state, declaring something or someone illegal is just a form of discrimination against the enemies of the state) to be declared as an enemy of the state (this status exist in different grades (i.e. "foreign agent", "undesired organization", "specially designated national", "felon" "criminal", "traitors of the nation", "enemies of the people", "fifth column" and so on) and doesn't necessarily needs to be explicitly publicly declared as such at all) and it is often illegal to help anyone in any way who was declared as an enemy of a state.

>Whoever, owing allegiance to the United States, levies war against them or **adheres to their enemies, giving them aid and comfort within the United States or elsewhere**, is guilty of treason and **shall suffer death**, or shall be imprisoned not less than five years and fined under this title but not less than $10,000; and shall be incapable of holding any office under the United States.

And states have powers to de-facto call anyone they decide as their enemies and de-facto declare a war on them and de-facto pursue their destruction. Up to real destruction, like [drone strikes](https://en.wikipedia.org/wiki/Disposition_Matrix) or [applying a poison on a doorknob](https://en.wikipedia.org/wiki/Poisoning_of_Sergei_and_Yulia_Skripal) or [underwear](https://en.wikipedia.org/wiki/Poisoning_of_Alexei_Navalny), or [with automated machineguns](https://en.wikipedia.org/wiki/Assassination_of_Iranian_nuclear_scientists) (is it illegal to do science and enginnering? Writing source code is also engineering... Those physicists were killed not because they did science or engineering, but because their existence was profiting enemies of some states, the same way existence and development of the software in question is profiting enemies of every state). But to be enforced the persons have to be within reach of that state, of course. If one dislikes US, one can beg for polytical asylium in North Korea, or Russia, as Snowden has done (I strongly advice against it), Iran, China or any other enough powerful state that are in cold or hot war with the rest of the world (but as you see, their capabilities to protect their assets are quite limited). But I doubt any state would be ready to give the asylium to the authors of the software mentioned. I consider more probable the creation of an international treaty (even with the participation of the outcast states) making it a felony for ordinary people (but explicitly allowing to intelligence community and elites) to use, create and use any kind (onion routing, cryptocurrencies, decentralyssd services in general, phone debloaters, jailbreaks, malicious content blockers (uBlock Origin, uMatrix, NoScript) and so on) of anti-surveillance software, the same way as the software circumventing Digital Restrictions Management has been criminalized in the most of jurisdictions.

So why does GH prohibits it? Because US prohibits GH (and anyone within US reach). If a state (maybe even a foreign one you are even not a citizen of) orders one to do/not to do something, one either obeys or becomes an enemy of that state and face consequencies if he is within reach of that state, if the state considers him worth the trouble.

You are an adult and educated person and it's a shame I had to explain you such basic things you should have got known yourself long ago.

**Comment by Karolakarola** [comment]
> /cc @matthewdgreen @tornadocash-admin
