### ISSUE TITLE
DMCA Takedown Notice Guide Drafting Suggestions

### ISSUE THREAD

**Issue by FranklinGraves** [github/site-policy#97]
This issue is about the "[Guide to Submitting a DMCA Takedown Notice](https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/)" and (arguably) confusing drafting language.

**The Problem** As drafted, GitHub's policy makes it seem as though anyone submitting a DMCA complaint is held to a higher-than-stautory notice requirement by asking for the inclusion of the affirmative statement: "I have read and understand GitHub's Guide to Filing a DMCA Notice." A plain reading of [17 U.S.C § 512](https://www.law.cornell.edu/uscode/text/17/512) contains no additional requirement for having read the GitHub DMCA Takedown Policy. Whether or not it allows for additional requirements is not an argument I'm making because I strongly believe the guides and template takedown notice provided by GitHub, as a whole, to be useful to the community. However, I'd like to explain the problem with one aspect of the way they are currently drafted.

Under the Guide, it is alluded to the possibility that not including this statement will adversely impact the response time to a DMCA Takedown Notice that is submitted. To be clear, I am not calling into question GitHub's overall compliance, or willingness to comply, with the DMCA process as may be required by law. However, I do think it is unclear and arguably misleading that a copyright owner or authorized representative who does not comply with GitHub's DMCA Takedown Policy, but maintains full compliance with the requirements of the statute, would potentially face an extended period of time before their otherwise proper DMCA Takedown Notice is handled by GitHub. At the very least, it may cause additional time of unnecessary research or review of the GitHub policy by a copyright owner or authorized representative (such has their legal counsel) before engaging in an otherwise notice submission process that is well understood by them through education or experience of their own.

**The Solution** I would propose changing [this section](https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/#your-complaint-must-) of the Guide's header from being "Your Complaint Must ..." to instead reading as "Your Complaint _Should_ ..." as well as removing the sentence "But we'll know that you haven't read these guidelines and may ask you to go back and do so." under the first item listed in this section of the Guide.

An alternative to completely striking the last sentence would be to modify it as follows: "But we'll know that you haven't read these guidelines and may ask you to go back and do so _in the event we receive an incomplete request_."

Thanks for reading and considering this suggestion!

**Comment by nsqe** [comment]
Hey, Franklin,

You raise some good points. However, I'm puzzled by your comment here: 

> Under the Guide, it is alluded to the possibility that not including this statement will adversely impact the response time to a DMCA Takedown Notice that is submitted.

I'm not sure where you're getting this impression from our Guidelines. As I read through the Guidelines, I don't see any reference to any adverse effect that leaving this statement out will have on the processing of a takedown request. To the contrary, we do state quite clearly that:

> We won't refuse to process an otherwise complete complaint if you don't include this statement. But we'll know that you haven't read these guidelines and may ask you to go back and do so.

We ask for an indication that filers have read our guidelines, because the vast majority of DMCA takedown requests we receive come from notice senders who don't have a legal background and generally don't have much experience filing takedown requests. We need them to read our policies and procedures so they are giving us all of the information we require. We try to make it as easy for them as possible, but if we find material deficiencies in a takedown request that show us that a user hasn't read our guidelines, we may send the user back to read through the document. 

We won't be able to change "Must" to "Should." There is only one element on that list that is optional under the statute and relevant case law, and that is the reference to the Guidelines; it would only be confusing to our users to have two separate lists. However, we'll take a look and consider adding the "in the event we receive an incomplete request" clarification, or similar language.

**Comment by FranklinGraves** [comment]
Thanks for the detailed response and consideration of clarifying the sentence in the Guide!

To quickly clarify and move on, I thought it beneficial for GitHub to know that, from one person's perspective, the phrasing of "But we'll know that you haven't read these guidelines and may ask you to go back and do so." leaves open the possibility of arbitrarily requiring the statement if it isn't included by a filer. Again, I am not questioning GitHub's policy for handling valid takedown requests by any stretch of the imagination. However, as I pointed out, it does unnecessarily cause someone that may otherwise understand how to submit a compliant takedown notice to stop and think about whether this additional requirement is truly necessary or not.

**Comment by nsqe** [comment]
Understood. No, we are not arbitrary, and we don't consider it a requirement. As the guideline indicates, we will process a fully-compliant DMCA takedown request that does not include the statement, but we'll look at a way to make that more clear.

Thanks!
